name: Game
source: 
author: 
license: 
rights_owner: 

max-output-size-K: 2096

limits: 
   timeout: 120

validator: 
   validatorProg: pc2.jar edu.csus.ecs.pc2.validator.Validator
   validatorCmd: '{:validator} {:infile} {:outfile} {:ansfile} {:resfile}  -pc2 1 false'
   usingInternal: true
   validatorOption: 1

input: 
   readFromSTDIN: true
